version: '3.8'
services:
    nginx:
      image: nginx:latest
      container_name: nginx-jose-nico
      ports:
      - "80:80"
      volumes:
      - ./html/static-website-example:/usr/share/nginx/html/static-website-example
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      restart: unless-stopped